name: Test, build & release

on:
  push:
    branches: [main, master]

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm test
        env:
          NODE_ENV: CI
      - name: Build package with SvelteKit
        run: npm run build
      - name: Run semantic release
        run: npx semantic-release --branches main
        working-directory: ./package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
